[package]
name = "flickerfix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.11"
tray-item = { version = "0.9.0", features = ["ksni"] }
