name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: sudo apt install libdbus-1-dev pkg-config && cargo build --verbose --release && chmod +x target/release/flickerfix
    - name: Update release
      uses: pyTooling/Actions/releaser@r0
      with:
        tag: latest
        rm: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: target/release/flickerfix
